src/Entity/Skill.php
<?php

namespace App\Entity;

use App\Component\AbstractEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SkillRepository")
 */
class Skill extends AbstractEntity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Gedmo\Translatable
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SkillGroup", inversedBy="skills")
     */
    private $skillGroup;

    /**
     * @ORM\Column(type="integer")
     */
    private $displayOrder;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getSkillGroup(): ?SkillGroup
    {
        return $this->skillGroup;
    }

    public function setSkillGroup(?SkillGroup $skillGroup): self
    {
        $this->skillGroup = $skillGroup;

        return $this;
    }

    public function getDisplayOrder(): ?int
    {
        return $this->displayOrder;
    }

    public function setDisplayOrder(int $displayOrder): self
    {
        $this->displayOrder = $displayOrder;

        return $this;
    }
	
	function getTitle()
	{
		return $this->getName();
	}
	
	function getSubTitle()
	{
		return "{$this->getLevel()}*";
	}
}

templates/abstract/edit.html.twig
{% extends 'hero.html.twig' %}

{% block title %}{% if item.id %}{{ 'Edit'|trans }} {% else %} {{ 'Create'|trans }} {% endif %} {{ title }} {% endblock %}

{% block body %}
<div class="column is-6 is-offset-3 has-text-centered">
    <h2 class="title">{% if item.id %}{{ 'Edit'|trans }} {% else %} {{ 'Create'|trans }} {% endif %} {{ title }}</h2>

    <div class="box">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="button is-fullwidth is-primary">
            <span class="icon">
              <i class="far fa-save"></i>
            </span>
        </button>
        {{ form_end(form) }}
    </div>

    <p>
        <a href="{{ path("#{route}index") }}">
            {{ 'Back to list'|trans }}
        </a>
    </p>

</div>
{% endblock %}

templates/abstract/index.html.twig
{% extends 'hero.html.twig' %}

{% block title %}{{ 'List'|trans }} {{ title }}{% endblock %}

{% block body %}
    <div class="columns is-mobile is-multiline is-centered">
        {% for item in items %}
            <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop is-one-quarter-fullhd">
                <div class="card">
                    <footer class="card-footer">
                        <a class="card-footer-item" href="{{ path("#{route}edit", {'id': item.id}) }}">
                            <span class="icon is-small">
                              <i class="far fa-edit"></i>
                            </span>
                        </a>
                        <a class="card-footer-item" href="{{ path("#{route}delete", {'id': item.id}) }}">
                            <span class="icon is-small">
                              <i class="far fa-trash-alt"></i>
                            </span>
                        </a>
                    </footer>
                </div>
                <div class="card-content">
                    <h2 class="title is-5">{{ item.title|nl2br }}</h2>
                    <p class="subtitle is-6">{{ item.subTitle|nl2br }}</p>
                </div>
            </div>
        {% endfor %}
        <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop is-one-quarter-fullhd">
            <div class="card">
                <div class="card-content">
                    {{ 'Actions'|trans }}
                </div>
                <footer class="card-footer">
                    <a class="card-footer-item" href="{{ path("#{route}new") }}">
                        <span class="icon is-small">
                          <i class="fas fa-plus"></i>
                        </span>
                    </a>
                </footer>
            </div>
        </div>
    </div>
{% endblock %}